name: Build And Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.16.0
      
      - name: Package Install
        run: npm install
        
      - name: before cache 
        run: |
          mkdir -p ~/go/pkg/mod
          ls ~/go/pkg/
      - name: cache  
        uses: actions/cache@v1
        with:
         id: cache-go
         path: ~/go/pkg/mod
         key: ${{ env.cache-version }}-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
         restore-keys: |
          ${{ runner.os }}-go-
      
      - name: Build
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to S3
        run: aws s3 sync ./build s3://react-bootstrap-portfolio-bucket

      - name: CloudFront Cache Clear
        run: CFID=352686643618:distribution/E2USIYE30MLM6V
          echo "aws cloudfront create-invalidation 352686643618:distribution/E2USIYE30MLM6V"
          aws cloudfront create-invalidation --distribution-id 352686643618:distribution/E2USIYE30MLM6V --paths "/*"
