name: UPload Website

on:
  push:
    branches:
      - main
      
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    
    - name: Build static file
      run: npm run build
      
    - name: Configure AWS Credentials
      uses: jakejarvis/s3-sync-action@main
      with:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./build s3://{ secrets.AWS_S3_BUCKET }
