name: Build React on S3
on:
  push:
      branches:
        - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master  # リポジトリをチェックアウト

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build  # React ビルド

      - name: Deploy  # S3にデプロイ 
        env:
          AWS_ACCESS_KEY_ID: ${{ AKIAVEHODDGRBXIII326 }}
          AWS_SECRET_ACCESS_KEY: ${{ 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 }}
        run: | # S3のreact-bootstrap-portfolio-bucketバケットにデプロイ
          aws s3 cp --recursive --region ap-northeast-1 build s3://react-bootstrap-portfolio-bucket
